# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from vtk.qt.QVTKRenderWindowInteractor import QVTKRenderWindowInteractor

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1908, 1050)
        MainWindow.setMinimumSize(QtCore.QSize(404, 215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_31.setSpacing(10)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_openfile = QtWidgets.QPushButton(self.centralwidget)
        self.btn_openfile.setMinimumSize(QtCore.QSize(120, 0))
        self.btn_openfile.setMaximumSize(QtCore.QSize(10000, 16777215))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_openfile.setFont(font)
        self.btn_openfile.setObjectName("btn_openfile")
        self.horizontalLayout.addWidget(self.btn_openfile)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMaximumSize(QtCore.QSize(10000, 16777215))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.comboBox_patient = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_patient.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBox_patient.setMaximumSize(QtCore.QSize(1000000, 16777215))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_patient.setFont(font)
        self.comboBox_patient.setObjectName("comboBox_patient")
        self.horizontalLayout.addWidget(self.comboBox_patient)
        self.btn_load = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_load.sizePolicy().hasHeightForWidth())
        self.btn_load.setSizePolicy(sizePolicy)
        self.btn_load.setMinimumSize(QtCore.QSize(120, 0))
        self.btn_load.setMaximumSize(QtCore.QSize(10000, 16777215))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_load.setFont(font)
        self.btn_load.setObjectName("btn_load")
        self.horizontalLayout.addWidget(self.btn_load)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 5)
        self.horizontalLayout.setStretch(3, 1)
        self.verticalLayout_21.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setSpacing(0)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.Page_T = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Page_T.setFont(font)
        self.Page_T.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(0, 0, 0);")
        self.Page_T.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Page_T.setObjectName("Page_T")
        self.horizontalLayout_17.addWidget(self.Page_T)
        self.WIN_T = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.WIN_T.setFont(font)
        self.WIN_T.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.WIN_T.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(0, 0, 0);")
        self.WIN_T.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.WIN_T.setObjectName("WIN_T")
        self.horizontalLayout_17.addWidget(self.WIN_T)
        self.horizontalLayout_17.setStretch(0, 1)
        self.horizontalLayout_17.setStretch(1, 1)
        self.verticalLayout_20.addLayout(self.horizontalLayout_17)
        self.label_T = QtWidgets.QLabel(self.centralwidget)
        self.label_T.setMinimumSize(QtCore.QSize(100, 100))
        self.label_T.setMaximumSize(QtCore.QSize(10000, 10000))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(10)
        self.label_T.setFont(font)
        self.label_T.setStyleSheet("background-color:rgb(0, 0, 0);")
        self.label_T.setText("")
        self.label_T.setScaledContents(False)
        self.label_T.setAlignment(QtCore.Qt.AlignCenter)
        self.label_T.setObjectName("label_T")
        self.verticalLayout_20.addWidget(self.label_T)
        self.verticalLayout_20.setStretch(0, 1)
        self.verticalLayout_20.setStretch(1, 10)
        self.horizontalLayout_30.addLayout(self.verticalLayout_20)
        self.Scroll_T = QtWidgets.QScrollBar(self.centralwidget)
        self.Scroll_T.setMinimumSize(QtCore.QSize(0, 0))
        self.Scroll_T.setOrientation(QtCore.Qt.Vertical)
        self.Scroll_T.setObjectName("Scroll_T")
        self.horizontalLayout_30.addWidget(self.Scroll_T)
        self.gridLayout.addLayout(self.horizontalLayout_30, 0, 0, 1, 1)
        self.vtkWidget = QVTKRenderWindowInteractor(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vtkWidget.sizePolicy().hasHeightForWidth())
        self.vtkWidget.setSizePolicy(sizePolicy)
        self.vtkWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.vtkWidget.setStyleSheet("background-color:rgb(0, 0, 0);")
        self.vtkWidget.setObjectName("vtkWidget")
        self.gridLayout.addWidget(self.vtkWidget, 0, 1, 1, 1)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setSpacing(0)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setSpacing(0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.Page_S = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Page_S.setFont(font)
        self.Page_S.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(0, 0, 0);")
        self.Page_S.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Page_S.setObjectName("Page_S")
        self.horizontalLayout_26.addWidget(self.Page_S)
        self.WIN_S = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.WIN_S.setFont(font)
        self.WIN_S.setAutoFillBackground(False)
        self.WIN_S.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(0, 0, 0);")
        self.WIN_S.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.WIN_S.setObjectName("WIN_S")
        self.horizontalLayout_26.addWidget(self.WIN_S)
        self.verticalLayout_9.addLayout(self.horizontalLayout_26)
        self.label_S = QtWidgets.QLabel(self.centralwidget)
        self.label_S.setMinimumSize(QtCore.QSize(100, 100))
        self.label_S.setMaximumSize(QtCore.QSize(10000, 10000))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(10)
        self.label_S.setFont(font)
        self.label_S.setStyleSheet("background-color:rgb(0, 0, 0);")
        self.label_S.setText("")
        self.label_S.setScaledContents(False)
        self.label_S.setAlignment(QtCore.Qt.AlignCenter)
        self.label_S.setObjectName("label_S")
        self.verticalLayout_9.addWidget(self.label_S)
        self.verticalLayout_9.setStretch(0, 1)
        self.verticalLayout_9.setStretch(1, 10)
        self.horizontalLayout_29.addLayout(self.verticalLayout_9)
        self.Scroll_S = QtWidgets.QScrollBar(self.centralwidget)
        self.Scroll_S.setMinimumSize(QtCore.QSize(0, 0))
        self.Scroll_S.setOrientation(QtCore.Qt.Vertical)
        self.Scroll_S.setObjectName("Scroll_S")
        self.horizontalLayout_29.addWidget(self.Scroll_S)
        self.gridLayout.addLayout(self.horizontalLayout_29, 1, 0, 1, 1)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setSpacing(0)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setSpacing(0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.Page_C = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Page_C.setFont(font)
        self.Page_C.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(0, 0, 0);")
        self.Page_C.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Page_C.setObjectName("Page_C")
        self.horizontalLayout_27.addWidget(self.Page_C)
        self.WIN_C = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.WIN_C.setFont(font)
        self.WIN_C.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(0, 0, 0);")
        self.WIN_C.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.WIN_C.setObjectName("WIN_C")
        self.horizontalLayout_27.addWidget(self.WIN_C)
        self.horizontalLayout_27.setStretch(0, 1)
        self.horizontalLayout_27.setStretch(1, 1)
        self.verticalLayout_19.addLayout(self.horizontalLayout_27)
        self.label_C = QtWidgets.QLabel(self.centralwidget)
        self.label_C.setMinimumSize(QtCore.QSize(100, 100))
        self.label_C.setMaximumSize(QtCore.QSize(10000, 10000))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(10)
        self.label_C.setFont(font)
        self.label_C.setStyleSheet("background-color:rgb(0, 0, 0);")
        self.label_C.setText("")
        self.label_C.setAlignment(QtCore.Qt.AlignCenter)
        self.label_C.setObjectName("label_C")
        self.verticalLayout_19.addWidget(self.label_C)
        self.verticalLayout_19.setStretch(0, 1)
        self.verticalLayout_19.setStretch(1, 10)
        self.horizontalLayout_28.addLayout(self.verticalLayout_19)
        self.Scroll_C = QtWidgets.QScrollBar(self.centralwidget)
        self.Scroll_C.setMinimumSize(QtCore.QSize(0, 0))
        self.Scroll_C.setOrientation(QtCore.Qt.Vertical)
        self.Scroll_C.setObjectName("Scroll_C")
        self.horizontalLayout_28.addWidget(self.Scroll_C)
        self.gridLayout.addLayout(self.horizontalLayout_28, 1, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 1)
        self.verticalLayout_21.addLayout(self.gridLayout)
        self.horizontalLayout_31.addLayout(self.verticalLayout_21)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.toolBox_2 = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox_2.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.toolBox_2.setFont(font)
        self.toolBox_2.setObjectName("toolBox_2")
        self.page11 = QtWidgets.QWidget()
        self.page11.setGeometry(QtCore.QRect(0, 0, 534, 373))
        self.page11.setObjectName("page11")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.page11)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.groupBox = QtWidgets.QGroupBox(self.page11)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.comboBox_farobj = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_farobj.sizePolicy().hasHeightForWidth())
        self.comboBox_farobj.setSizePolicy(sizePolicy)
        self.comboBox_farobj.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_farobj.setMaximumSize(QtCore.QSize(10000, 16777215))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        self.comboBox_farobj.setFont(font)
        self.comboBox_farobj.setObjectName("comboBox_farobj")
        self.horizontalLayout_10.addWidget(self.comboBox_farobj)
        self.horizontalLayout_10.setStretch(0, 1)
        self.horizontalLayout_10.setStretch(1, 5)
        self.verticalLayout_24.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_13.addWidget(self.label_10)
        self.comboBox_sonobj = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_sonobj.sizePolicy().hasHeightForWidth())
        self.comboBox_sonobj.setSizePolicy(sizePolicy)
        self.comboBox_sonobj.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_sonobj.setMaximumSize(QtCore.QSize(10000, 16777215))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        self.comboBox_sonobj.setFont(font)
        self.comboBox_sonobj.setObjectName("comboBox_sonobj")
        self.horizontalLayout_13.addWidget(self.comboBox_sonobj)
        self.horizontalLayout_13.setStretch(0, 1)
        self.horizontalLayout_13.setStretch(1, 5)
        self.verticalLayout_24.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.btn_chosecolor = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_chosecolor.sizePolicy().hasHeightForWidth())
        self.btn_chosecolor.setSizePolicy(sizePolicy)
        self.btn_chosecolor.setObjectName("btn_chosecolor")
        self.horizontalLayout_16.addWidget(self.btn_chosecolor)
        self.btn_delobj = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_delobj.sizePolicy().hasHeightForWidth())
        self.btn_delobj.setSizePolicy(sizePolicy)
        self.btn_delobj.setMaximumSize(QtCore.QSize(10000, 16777215))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        self.btn_delobj.setFont(font)
        self.btn_delobj.setObjectName("btn_delobj")
        self.horizontalLayout_16.addWidget(self.btn_delobj)
        self.btn_default_scene = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_default_scene.sizePolicy().hasHeightForWidth())
        self.btn_default_scene.setSizePolicy(sizePolicy)
        self.btn_default_scene.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_default_scene.setMaximumSize(QtCore.QSize(10000, 16777215))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        self.btn_default_scene.setFont(font)
        self.btn_default_scene.setObjectName("btn_default_scene")
        self.horizontalLayout_16.addWidget(self.btn_default_scene)
        self.horizontalLayout_16.setStretch(0, 1)
        self.horizontalLayout_16.setStretch(1, 1)
        self.horizontalLayout_16.setStretch(2, 1)
        self.verticalLayout_24.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_18.addWidget(self.label_6)
        self.label_29 = QtWidgets.QLabel(self.groupBox)
        self.label_29.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_18.addWidget(self.label_29)
        self.label_32 = QtWidgets.QLabel(self.groupBox)
        self.label_32.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_18.addWidget(self.label_32)
        self.horizontalLayout_19.addLayout(self.verticalLayout_18)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout()
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.label_TMIN = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_TMIN.setFont(font)
        self.label_TMIN.setObjectName("label_TMIN")
        self.horizontalLayout_43.addWidget(self.label_TMIN)
        self.label_TNOW = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_TNOW.setFont(font)
        self.label_TNOW.setAlignment(QtCore.Qt.AlignCenter)
        self.label_TNOW.setObjectName("label_TNOW")
        self.horizontalLayout_43.addWidget(self.label_TNOW)
        self.label_TMAX = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_TMAX.setFont(font)
        self.label_TMAX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_TMAX.setObjectName("label_TMAX")
        self.horizontalLayout_43.addWidget(self.label_TMAX)
        self.horizontalLayout_43.setStretch(0, 1)
        self.horizontalLayout_43.setStretch(1, 1)
        self.horizontalLayout_43.setStretch(2, 1)
        self.verticalLayout_31.addLayout(self.horizontalLayout_43)
        self.T_Slider = QtWidgets.QSlider(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.T_Slider.sizePolicy().hasHeightForWidth())
        self.T_Slider.setSizePolicy(sizePolicy)
        self.T_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.T_Slider.setObjectName("T_Slider")
        self.verticalLayout_31.addWidget(self.T_Slider)
        self.verticalLayout_31.setStretch(0, 1)
        self.verticalLayout_31.setStretch(1, 1)
        self.verticalLayout_22.addLayout(self.verticalLayout_31)
        self.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.label_RMIN = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_RMIN.setFont(font)
        self.label_RMIN.setObjectName("label_RMIN")
        self.horizontalLayout_45.addWidget(self.label_RMIN)
        self.label_RNOW = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_RNOW.setFont(font)
        self.label_RNOW.setAlignment(QtCore.Qt.AlignCenter)
        self.label_RNOW.setObjectName("label_RNOW")
        self.horizontalLayout_45.addWidget(self.label_RNOW)
        self.label_RMAX = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_RMAX.setFont(font)
        self.label_RMAX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RMAX.setObjectName("label_RMAX")
        self.horizontalLayout_45.addWidget(self.label_RMAX)
        self.verticalLayout_32.addLayout(self.horizontalLayout_45)
        self.R_Slider = QtWidgets.QSlider(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R_Slider.sizePolicy().hasHeightForWidth())
        self.R_Slider.setSizePolicy(sizePolicy)
        self.R_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.R_Slider.setObjectName("R_Slider")
        self.verticalLayout_32.addWidget(self.R_Slider)
        self.verticalLayout_22.addLayout(self.verticalLayout_32)
        self.verticalLayout_38 = QtWidgets.QVBoxLayout()
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.label_KMIN = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_KMIN.setFont(font)
        self.label_KMIN.setObjectName("label_KMIN")
        self.horizontalLayout_46.addWidget(self.label_KMIN)
        self.label_KNOW = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_KNOW.setFont(font)
        self.label_KNOW.setAlignment(QtCore.Qt.AlignCenter)
        self.label_KNOW.setObjectName("label_KNOW")
        self.horizontalLayout_46.addWidget(self.label_KNOW)
        self.label_KMAX = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_KMAX.setFont(font)
        self.label_KMAX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_KMAX.setObjectName("label_KMAX")
        self.horizontalLayout_46.addWidget(self.label_KMAX)
        self.verticalLayout_38.addLayout(self.horizontalLayout_46)
        self.K_Slider = QtWidgets.QSlider(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K_Slider.sizePolicy().hasHeightForWidth())
        self.K_Slider.setSizePolicy(sizePolicy)
        self.K_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.K_Slider.setObjectName("K_Slider")
        self.verticalLayout_38.addWidget(self.K_Slider)
        self.verticalLayout_22.addLayout(self.verticalLayout_38)
        self.verticalLayout_22.setStretch(0, 1)
        self.verticalLayout_22.setStretch(1, 1)
        self.verticalLayout_22.setStretch(2, 1)
        self.horizontalLayout_19.addLayout(self.verticalLayout_22)
        self.verticalLayout_24.addLayout(self.horizontalLayout_19)
        self.verticalLayout_24.setStretch(0, 1)
        self.verticalLayout_24.setStretch(1, 1)
        self.verticalLayout_24.setStretch(2, 1)
        self.verticalLayout_24.setStretch(3, 6)
        self.verticalLayout_26.addLayout(self.verticalLayout_24)
        self.verticalLayout_27.addWidget(self.groupBox)
        self.toolBox_2.addItem(self.page11, "")
        self.verticalLayout_17.addWidget(self.toolBox_2)
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setMinimumSize(QtCore.QSize(10, 0))
        self.toolBox.setMaximumSize(QtCore.QSize(10000, 16777215))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.toolBox.setFont(font)
        self.toolBox.setStyleSheet("\n"
"")
        self.toolBox.setObjectName("toolBox")
        self.abparam_page = QtWidgets.QWidget()
        self.abparam_page.setGeometry(QtCore.QRect(0, 0, 534, 506))
        self.abparam_page.setObjectName("abparam_page")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.abparam_page)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.btn_mark = QtWidgets.QPushButton(self.abparam_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_mark.sizePolicy().hasHeightForWidth())
        self.btn_mark.setSizePolicy(sizePolicy)
        self.btn_mark.setMaximumSize(QtCore.QSize(10000, 16777215))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_mark.setFont(font)
        self.btn_mark.setStyleSheet("")
        self.btn_mark.setObjectName("btn_mark")
        self.verticalLayout_23.addWidget(self.btn_mark)
        self.groupBox_3 = QtWidgets.QGroupBox(self.abparam_page)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_searchlabelled = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_searchlabelled.sizePolicy().hasHeightForWidth())
        self.btn_searchlabelled.setSizePolicy(sizePolicy)
        self.btn_searchlabelled.setMaximumSize(QtCore.QSize(1000, 16777215))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_searchlabelled.setFont(font)
        self.btn_searchlabelled.setObjectName("btn_searchlabelled")
        self.verticalLayout_3.addWidget(self.btn_searchlabelled)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_16.addWidget(self.label_3)
        self.label_25 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_16.addWidget(self.label_25)
        self.label_26 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_16.addWidget(self.label_26)
        self.horizontalLayout_21.addLayout(self.verticalLayout_16)
        self.verticalLayout_39 = QtWidgets.QVBoxLayout()
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.comboBox_labelled_case = QtWidgets.QComboBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_labelled_case.sizePolicy().hasHeightForWidth())
        self.comboBox_labelled_case.setSizePolicy(sizePolicy)
        self.comboBox_labelled_case.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.comboBox_labelled_case.setFont(font)
        self.comboBox_labelled_case.setObjectName("comboBox_labelled_case")
        self.verticalLayout_39.addWidget(self.comboBox_labelled_case)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.comboBox_targets_hand = QtWidgets.QComboBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_targets_hand.sizePolicy().hasHeightForWidth())
        self.comboBox_targets_hand.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.comboBox_targets_hand.setFont(font)
        self.comboBox_targets_hand.setObjectName("comboBox_targets_hand")
        self.horizontalLayout_15.addWidget(self.comboBox_targets_hand)
        self.btn_del_target = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_del_target.sizePolicy().hasHeightForWidth())
        self.btn_del_target.setSizePolicy(sizePolicy)
        self.btn_del_target.setMaximumSize(QtCore.QSize(10000, 16777215))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_del_target.setFont(font)
        self.btn_del_target.setObjectName("btn_del_target")
        self.horizontalLayout_15.addWidget(self.btn_del_target)
        self.horizontalLayout_15.setStretch(0, 6)
        self.horizontalLayout_15.setStretch(1, 1)
        self.verticalLayout_39.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.comboBox_inpts_hand = QtWidgets.QComboBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_inpts_hand.sizePolicy().hasHeightForWidth())
        self.comboBox_inpts_hand.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.comboBox_inpts_hand.setFont(font)
        self.comboBox_inpts_hand.setObjectName("comboBox_inpts_hand")
        self.horizontalLayout_20.addWidget(self.comboBox_inpts_hand)
        self.btn_del_inpt = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_del_inpt.sizePolicy().hasHeightForWidth())
        self.btn_del_inpt.setSizePolicy(sizePolicy)
        self.btn_del_inpt.setMaximumSize(QtCore.QSize(10000, 16777215))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_del_inpt.setFont(font)
        self.btn_del_inpt.setObjectName("btn_del_inpt")
        self.horizontalLayout_20.addWidget(self.btn_del_inpt)
        self.horizontalLayout_20.setStretch(0, 6)
        self.horizontalLayout_20.setStretch(1, 1)
        self.verticalLayout_39.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21.addLayout(self.verticalLayout_39)
        self.horizontalLayout_21.setStretch(0, 1)
        self.horizontalLayout_21.setStretch(1, 4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_21)
        self.btn_addto_path = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_addto_path.sizePolicy().hasHeightForWidth())
        self.btn_addto_path.setSizePolicy(sizePolicy)
        self.btn_addto_path.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_addto_path.setMaximumSize(QtCore.QSize(10000, 16777215))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_addto_path.setFont(font)
        self.btn_addto_path.setObjectName("btn_addto_path")
        self.verticalLayout_3.addWidget(self.btn_addto_path)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 3)
        self.verticalLayout_3.setStretch(2, 1)
        self.verticalLayout_14.addLayout(self.verticalLayout_3)
        self.verticalLayout_23.addWidget(self.groupBox_3)
        self.btn_clear_hand = QtWidgets.QPushButton(self.abparam_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_clear_hand.sizePolicy().hasHeightForWidth())
        self.btn_clear_hand.setSizePolicy(sizePolicy)
        self.btn_clear_hand.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_clear_hand.setFont(font)
        self.btn_clear_hand.setObjectName("btn_clear_hand")
        self.verticalLayout_23.addWidget(self.btn_clear_hand)
        self.verticalLayout_23.setStretch(0, 1)
        self.verticalLayout_23.setStretch(1, 6)
        self.verticalLayout_23.setStretch(2, 1)
        self.verticalLayout_28.addLayout(self.verticalLayout_23)
        self.toolBox.addItem(self.abparam_page, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 513, 514))
        self.page_3.setObjectName("page_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.groupBox_5 = QtWidgets.QGroupBox(self.page_3)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_assign_target = QtWidgets.QPushButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_assign_target.sizePolicy().hasHeightForWidth())
        self.btn_assign_target.setSizePolicy(sizePolicy)
        self.btn_assign_target.setMaximumSize(QtCore.QSize(10000, 16777215))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_assign_target.setFont(font)
        self.btn_assign_target.setObjectName("btn_assign_target")
        self.horizontalLayout_3.addWidget(self.btn_assign_target)
        self.horizontalLayout_3.setStretch(0, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label = QtWidgets.QLabel(self.groupBox_5)
        self.label.setMaximumSize(QtCore.QSize(10000, 16777215))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_25.addWidget(self.label)
        self.comboBox_targets_auto1 = QtWidgets.QComboBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_targets_auto1.sizePolicy().hasHeightForWidth())
        self.comboBox_targets_auto1.setSizePolicy(sizePolicy)
        self.comboBox_targets_auto1.setMinimumSize(QtCore.QSize(10, 0))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_targets_auto1.setFont(font)
        self.comboBox_targets_auto1.setObjectName("comboBox_targets_auto1")
        self.horizontalLayout_25.addWidget(self.comboBox_targets_auto1)
        self.btn_del_tars_auto1 = QtWidgets.QPushButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_del_tars_auto1.sizePolicy().hasHeightForWidth())
        self.btn_del_tars_auto1.setSizePolicy(sizePolicy)
        self.btn_del_tars_auto1.setMaximumSize(QtCore.QSize(10000, 16777215))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_del_tars_auto1.setFont(font)
        self.btn_del_tars_auto1.setObjectName("btn_del_tars_auto1")
        self.horizontalLayout_25.addWidget(self.btn_del_tars_auto1)
        self.horizontalLayout_25.setStretch(0, 1)
        self.horizontalLayout_25.setStretch(1, 5)
        self.horizontalLayout_25.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btn_get_feasible_auto1 = QtWidgets.QPushButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_get_feasible_auto1.sizePolicy().hasHeightForWidth())
        self.btn_get_feasible_auto1.setSizePolicy(sizePolicy)
        self.btn_get_feasible_auto1.setMaximumSize(QtCore.QSize(10000, 16777215))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_get_feasible_auto1.setFont(font)
        self.btn_get_feasible_auto1.setObjectName("btn_get_feasible_auto1")
        self.horizontalLayout_6.addWidget(self.btn_get_feasible_auto1)
        self.btn_NSGA = QtWidgets.QPushButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_NSGA.sizePolicy().hasHeightForWidth())
        self.btn_NSGA.setSizePolicy(sizePolicy)
        self.btn_NSGA.setMinimumSize(QtCore.QSize(10, 0))
        self.btn_NSGA.setMaximumSize(QtCore.QSize(10000, 16777215))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_NSGA.setFont(font)
        self.btn_NSGA.setObjectName("btn_NSGA")
        self.horizontalLayout_6.addWidget(self.btn_NSGA)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.verticalLayout_15.addLayout(self.verticalLayout)
        self.verticalLayout_10.addWidget(self.groupBox_5)
        self.groupBox_7 = QtWidgets.QGroupBox(self.page_3)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.comboBox_pareto_auto1 = QtWidgets.QComboBox(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_pareto_auto1.sizePolicy().hasHeightForWidth())
        self.comboBox_pareto_auto1.setSizePolicy(sizePolicy)
        self.comboBox_pareto_auto1.setMinimumSize(QtCore.QSize(10, 0))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_pareto_auto1.setFont(font)
        self.comboBox_pareto_auto1.setObjectName("comboBox_pareto_auto1")
        self.horizontalLayout_8.addWidget(self.comboBox_pareto_auto1)
        self.btn_chose_pareto = QtWidgets.QPushButton(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_chose_pareto.sizePolicy().hasHeightForWidth())
        self.btn_chose_pareto.setSizePolicy(sizePolicy)
        self.btn_chose_pareto.setMinimumSize(QtCore.QSize(10, 0))
        self.btn_chose_pareto.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_chose_pareto.setFont(font)
        self.btn_chose_pareto.setObjectName("btn_chose_pareto")
        self.horizontalLayout_8.addWidget(self.btn_chose_pareto)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_8)
        self.verticalLayout_10.addWidget(self.groupBox_7)
        self.groupBox_17 = QtWidgets.QGroupBox(self.page_3)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_17.setFont(font)
        self.groupBox_17.setObjectName("groupBox_17")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.groupBox_17)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_30 = QtWidgets.QLabel(self.groupBox_17)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_7.addWidget(self.label_30)
        self.label_38 = QtWidgets.QLabel(self.groupBox_17)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_7.addWidget(self.label_38)
        self.label_40 = QtWidgets.QLabel(self.groupBox_17)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_7.addWidget(self.label_40)
        self.verticalLayout_7.setStretch(0, 1)
        self.verticalLayout_7.setStretch(1, 1)
        self.verticalLayout_7.setStretch(2, 1)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_distmax = QtWidgets.QLabel(self.groupBox_17)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_distmax.setFont(font)
        self.label_distmax.setObjectName("label_distmax")
        self.horizontalLayout_4.addWidget(self.label_distmax)
        self.label_distnow = QtWidgets.QLabel(self.groupBox_17)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_distnow.setFont(font)
        self.label_distnow.setAlignment(QtCore.Qt.AlignCenter)
        self.label_distnow.setObjectName("label_distnow")
        self.horizontalLayout_4.addWidget(self.label_distnow)
        self.label_distmin = QtWidgets.QLabel(self.groupBox_17)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_distmin.setFont(font)
        self.label_distmin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_distmin.setObjectName("label_distmin")
        self.horizontalLayout_4.addWidget(self.label_distmin)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 1)
        self.horizontalLayout_4.setStretch(2, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.dist_Slider = QtWidgets.QSlider(self.groupBox_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dist_Slider.sizePolicy().hasHeightForWidth())
        self.dist_Slider.setSizePolicy(sizePolicy)
        self.dist_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.dist_Slider.setObjectName("dist_Slider")
        self.verticalLayout_4.addWidget(self.dist_Slider)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 1)
        self.verticalLayout_11.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_anglemax = QtWidgets.QLabel(self.groupBox_17)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_anglemax.setFont(font)
        self.label_anglemax.setObjectName("label_anglemax")
        self.horizontalLayout_9.addWidget(self.label_anglemax)
        self.label_anglenow = QtWidgets.QLabel(self.groupBox_17)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_anglenow.setFont(font)
        self.label_anglenow.setAlignment(QtCore.Qt.AlignCenter)
        self.label_anglenow.setObjectName("label_anglenow")
        self.horizontalLayout_9.addWidget(self.label_anglenow)
        self.label_anglemin = QtWidgets.QLabel(self.groupBox_17)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_anglemin.setFont(font)
        self.label_anglemin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_anglemin.setObjectName("label_anglemin")
        self.horizontalLayout_9.addWidget(self.label_anglemin)
        self.horizontalLayout_9.setStretch(0, 1)
        self.horizontalLayout_9.setStretch(1, 1)
        self.horizontalLayout_9.setStretch(2, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.angle_Slider = QtWidgets.QSlider(self.groupBox_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.angle_Slider.sizePolicy().hasHeightForWidth())
        self.angle_Slider.setSizePolicy(sizePolicy)
        self.angle_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.angle_Slider.setObjectName("angle_Slider")
        self.verticalLayout_5.addWidget(self.angle_Slider)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_5.setStretch(1, 1)
        self.verticalLayout_11.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_riskmax = QtWidgets.QLabel(self.groupBox_17)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_riskmax.setFont(font)
        self.label_riskmax.setObjectName("label_riskmax")
        self.horizontalLayout_11.addWidget(self.label_riskmax)
        self.label_risknow = QtWidgets.QLabel(self.groupBox_17)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_risknow.setFont(font)
        self.label_risknow.setAlignment(QtCore.Qt.AlignCenter)
        self.label_risknow.setObjectName("label_risknow")
        self.horizontalLayout_11.addWidget(self.label_risknow)
        self.label_riskmin = QtWidgets.QLabel(self.groupBox_17)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_riskmin.setFont(font)
        self.label_riskmin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_riskmin.setObjectName("label_riskmin")
        self.horizontalLayout_11.addWidget(self.label_riskmin)
        self.horizontalLayout_11.setStretch(0, 1)
        self.horizontalLayout_11.setStretch(1, 1)
        self.horizontalLayout_11.setStretch(2, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.risk_Slider = QtWidgets.QSlider(self.groupBox_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.risk_Slider.sizePolicy().hasHeightForWidth())
        self.risk_Slider.setSizePolicy(sizePolicy)
        self.risk_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.risk_Slider.setObjectName("risk_Slider")
        self.verticalLayout_6.addWidget(self.risk_Slider)
        self.verticalLayout_6.setStretch(0, 1)
        self.verticalLayout_6.setStretch(1, 1)
        self.verticalLayout_11.addLayout(self.verticalLayout_6)
        self.verticalLayout_11.setStretch(0, 1)
        self.verticalLayout_11.setStretch(1, 1)
        self.verticalLayout_11.setStretch(2, 1)
        self.horizontalLayout_5.addLayout(self.verticalLayout_11)
        self.horizontalLayout_5.setStretch(0, 2)
        self.horizontalLayout_5.setStretch(1, 3)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_5)
        self.verticalLayout_10.addWidget(self.groupBox_17)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.btn_fresh_pareto = QtWidgets.QPushButton(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_fresh_pareto.sizePolicy().hasHeightForWidth())
        self.btn_fresh_pareto.setSizePolicy(sizePolicy)
        self.btn_fresh_pareto.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_fresh_pareto.setFont(font)
        self.btn_fresh_pareto.setObjectName("btn_fresh_pareto")
        self.horizontalLayout_23.addWidget(self.btn_fresh_pareto)
        self.btn_clear_auto1 = QtWidgets.QPushButton(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_clear_auto1.sizePolicy().hasHeightForWidth())
        self.btn_clear_auto1.setSizePolicy(sizePolicy)
        self.btn_clear_auto1.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_clear_auto1.setFont(font)
        self.btn_clear_auto1.setObjectName("btn_clear_auto1")
        self.horizontalLayout_23.addWidget(self.btn_clear_auto1)
        self.horizontalLayout_23.setStretch(0, 1)
        self.horizontalLayout_23.setStretch(1, 1)
        self.verticalLayout_10.addLayout(self.horizontalLayout_23)
        self.toolBox.addItem(self.page_3, "")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 534, 506))
        self.page.setObjectName("page")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.groupBox_2 = QtWidgets.QGroupBox(self.page)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_35 = QtWidgets.QLabel(self.groupBox_2)
        self.label_35.setMinimumSize(QtCore.QSize(0, 0))
        self.label_35.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_33.addWidget(self.label_35)
        self.comboBox_tmrs_auto2 = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_tmrs_auto2.sizePolicy().hasHeightForWidth())
        self.comboBox_tmrs_auto2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_tmrs_auto2.setFont(font)
        self.comboBox_tmrs_auto2.setObjectName("comboBox_tmrs_auto2")
        self.horizontalLayout_33.addWidget(self.comboBox_tmrs_auto2)
        self.horizontalLayout_34.addLayout(self.horizontalLayout_33)
        self.verticalLayout_12.addWidget(self.groupBox_2)
        self.groupBox_11 = QtWidgets.QGroupBox(self.page)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_getabnum_auto2 = QtWidgets.QPushButton(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_getabnum_auto2.sizePolicy().hasHeightForWidth())
        self.btn_getabnum_auto2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_getabnum_auto2.setFont(font)
        self.btn_getabnum_auto2.setObjectName("btn_getabnum_auto2")
        self.verticalLayout_2.addWidget(self.btn_getabnum_auto2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_33 = QtWidgets.QLabel(self.groupBox_11)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_7.addWidget(self.label_33)
        self.lineEdit_abnum_auto2 = QtWidgets.QLineEdit(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_abnum_auto2.sizePolicy().hasHeightForWidth())
        self.lineEdit_abnum_auto2.setSizePolicy(sizePolicy)
        self.lineEdit_abnum_auto2.setMaximumSize(QtCore.QSize(10000, 16777215))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_abnum_auto2.setFont(font)
        self.lineEdit_abnum_auto2.setObjectName("lineEdit_abnum_auto2")
        self.horizontalLayout_7.addWidget(self.lineEdit_abnum_auto2)
        self.horizontalLayout_7.setStretch(0, 2)
        self.horizontalLayout_7.setStretch(1, 3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_18.addLayout(self.verticalLayout_2)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.btn_getpnum_auto2 = QtWidgets.QPushButton(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_getpnum_auto2.sizePolicy().hasHeightForWidth())
        self.btn_getpnum_auto2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_getpnum_auto2.setFont(font)
        self.btn_getpnum_auto2.setObjectName("btn_getpnum_auto2")
        self.verticalLayout_8.addWidget(self.btn_getpnum_auto2)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_34 = QtWidgets.QLabel(self.groupBox_11)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_14.addWidget(self.label_34)
        self.lineEdit_pnum_auto2 = QtWidgets.QLineEdit(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pnum_auto2.sizePolicy().hasHeightForWidth())
        self.lineEdit_pnum_auto2.setSizePolicy(sizePolicy)
        self.lineEdit_pnum_auto2.setMaximumSize(QtCore.QSize(10000, 16777215))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_pnum_auto2.setFont(font)
        self.lineEdit_pnum_auto2.setObjectName("lineEdit_pnum_auto2")
        self.horizontalLayout_14.addWidget(self.lineEdit_pnum_auto2)
        self.horizontalLayout_14.setStretch(0, 2)
        self.horizontalLayout_14.setStretch(1, 3)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_18.addLayout(self.verticalLayout_8)
        self.horizontalLayout_18.setStretch(0, 1)
        self.horizontalLayout_18.setStretch(1, 1)
        self.verticalLayout_13.addLayout(self.horizontalLayout_18)
        self.btn_getfea_auto2 = QtWidgets.QPushButton(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_getfea_auto2.sizePolicy().hasHeightForWidth())
        self.btn_getfea_auto2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_getfea_auto2.setFont(font)
        self.btn_getfea_auto2.setObjectName("btn_getfea_auto2")
        self.verticalLayout_13.addWidget(self.btn_getfea_auto2)
        self.verticalLayout_13.setStretch(0, 2)
        self.verticalLayout_13.setStretch(1, 1)
        self.verticalLayout_25.addLayout(self.verticalLayout_13)
        self.verticalLayout_12.addWidget(self.groupBox_11)
        self.groupBox_12 = QtWidgets.QGroupBox(self.page)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox_12.setFont(font)
        self.groupBox_12.setObjectName("groupBox_12")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout(self.groupBox_12)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_43 = QtWidgets.QLabel(self.groupBox_12)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_35.addWidget(self.label_43)
        self.comboBox_schemes_auto2 = QtWidgets.QComboBox(self.groupBox_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_schemes_auto2.sizePolicy().hasHeightForWidth())
        self.comboBox_schemes_auto2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_schemes_auto2.setFont(font)
        self.comboBox_schemes_auto2.setObjectName("comboBox_schemes_auto2")
        self.horizontalLayout_35.addWidget(self.comboBox_schemes_auto2)
        self.horizontalLayout_35.setStretch(0, 2)
        self.horizontalLayout_35.setStretch(1, 3)
        self.horizontalLayout_36.addLayout(self.horizontalLayout_35)
        self.verticalLayout_12.addWidget(self.groupBox_12)
        self.btn_clear_auto2 = QtWidgets.QPushButton(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_clear_auto2.sizePolicy().hasHeightForWidth())
        self.btn_clear_auto2.setSizePolicy(sizePolicy)
        self.btn_clear_auto2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_clear_auto2.setFont(font)
        self.btn_clear_auto2.setObjectName("btn_clear_auto2")
        self.verticalLayout_12.addWidget(self.btn_clear_auto2)
        self.verticalLayout_12.setStretch(0, 2)
        self.verticalLayout_12.setStretch(1, 5)
        self.verticalLayout_12.setStretch(2, 2)
        self.verticalLayout_12.setStretch(3, 1)
        self.toolBox.addItem(self.page, "")
        self.verticalLayout_17.addWidget(self.toolBox)
        self.verticalLayout_17.setStretch(0, 4)
        self.verticalLayout_17.setStretch(1, 6)
        self.horizontalLayout_31.addLayout(self.verticalLayout_17)
        self.horizontalLayout_31.setStretch(0, 5)
        self.horizontalLayout_31.setStretch(1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.toolBox_2.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_openfile.setText(_translate("MainWindow", "打开"))
        self.label_4.setText(_translate("MainWindow", "病例名"))
        self.btn_load.setText(_translate("MainWindow", "载入"))
        self.Page_T.setText(_translate("MainWindow", " 0/0"))
        self.WIN_T.setText(_translate("MainWindow", "T "))
        self.Page_S.setText(_translate("MainWindow", " 0/0"))
        self.WIN_S.setText(_translate("MainWindow", "S "))
        self.Page_C.setText(_translate("MainWindow", " 0/0"))
        self.WIN_C.setText(_translate("MainWindow", "C "))
        self.groupBox.setTitle(_translate("MainWindow", "场景对象管理"))
        self.label_9.setText(_translate("MainWindow", "对象类型"))
        self.label_10.setText(_translate("MainWindow", "对象列表"))
        self.btn_chosecolor.setText(_translate("MainWindow", "修改颜色"))
        self.btn_delobj.setText(_translate("MainWindow", "删除对象"))
        self.btn_default_scene.setText(_translate("MainWindow", "恢复默认"))
        self.label_6.setText(_translate("MainWindow", "透明度"))
        self.label_29.setText(_translate("MainWindow", "消融长轴半径(mm)"))
        self.label_32.setText(_translate("MainWindow", "消融长短轴比"))
        self.label_TMIN.setText(_translate("MainWindow", "0"))
        self.label_TNOW.setText(_translate("MainWindow", "0"))
        self.label_TMAX.setText(_translate("MainWindow", "1"))
        self.label_RMIN.setText(_translate("MainWindow", "13"))
        self.label_RNOW.setText(_translate("MainWindow", "13"))
        self.label_RMAX.setText(_translate("MainWindow", "26"))
        self.label_KMIN.setText(_translate("MainWindow", "1"))
        self.label_KNOW.setText(_translate("MainWindow", "1"))
        self.label_KMAX.setText(_translate("MainWindow", "2"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page11), _translate("MainWindow", "参数设置"))
        self.btn_mark.setText(_translate("MainWindow", "标记当前层"))
        self.groupBox_3.setTitle(_translate("MainWindow", "进针方案制定"))
        self.btn_searchlabelled.setText(_translate("MainWindow", "查询当前已标记病例"))
        self.label_3.setText(_translate("MainWindow", "已标记病例"))
        self.label_25.setText(_translate("MainWindow", "靶点"))
        self.label_26.setText(_translate("MainWindow", "进针点"))
        self.btn_del_target.setText(_translate("MainWindow", "删除"))
        self.btn_del_inpt.setText(_translate("MainWindow", "删除"))
        self.btn_addto_path.setText(_translate("MainWindow", "加入进针方案"))
        self.btn_clear_hand.setText(_translate("MainWindow", "清空当前规划结果"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.abparam_page), _translate("MainWindow", "手动规划"))
        self.groupBox_5.setTitle(_translate("MainWindow", "优化"))
        self.btn_assign_target.setText(_translate("MainWindow", "添加靶点"))
        self.label.setText(_translate("MainWindow", "靶点"))
        self.btn_del_tars_auto1.setText(_translate("MainWindow", "删除"))
        self.btn_get_feasible_auto1.setText(_translate("MainWindow", "计算可行域"))
        self.btn_NSGA.setText(_translate("MainWindow", "优化"))
        self.groupBox_7.setTitle(_translate("MainWindow", "帕累托点列表"))
        self.btn_chose_pareto.setText(_translate("MainWindow", "选择"))
        self.groupBox_17.setTitle(_translate("MainWindow", "帕累托点筛选"))
        self.label_30.setText(_translate("MainWindow", "到靶点距离≤(mm)"))
        self.label_38.setText(_translate("MainWindow", "与靶点纵向角度差≤"))
        self.label_40.setText(_translate("MainWindow", "到障碍距离≥(mm)"))
        self.label_distmax.setText(_translate("MainWindow", "0"))
        self.label_distnow.setText(_translate("MainWindow", "0"))
        self.label_distmin.setText(_translate("MainWindow", "0"))
        self.label_anglemax.setText(_translate("MainWindow", "0"))
        self.label_anglenow.setText(_translate("MainWindow", "0"))
        self.label_anglemin.setText(_translate("MainWindow", "0"))
        self.label_riskmax.setText(_translate("MainWindow", "0"))
        self.label_risknow.setText(_translate("MainWindow", "0"))
        self.label_riskmin.setText(_translate("MainWindow", "0"))
        self.btn_fresh_pareto.setText(_translate("MainWindow", "更新帕累托点显示"))
        self.btn_clear_auto1.setText(_translate("MainWindow", "清空当前规划结果"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "逐针规划"))
        self.groupBox_2.setTitle(_translate("MainWindow", "选择规划对象"))
        self.label_35.setText(_translate("MainWindow", "规划对象"))
        self.groupBox_11.setTitle(_translate("MainWindow", "优化模型计算"))
        self.btn_getabnum_auto2.setText(_translate("MainWindow", "确定消融次数"))
        self.label_33.setText(_translate("MainWindow", "消融数"))
        self.btn_getpnum_auto2.setText(_translate("MainWindow", "确定进针次数"))
        self.label_34.setText(_translate("MainWindow", "进针数"))
        self.btn_getfea_auto2.setText(_translate("MainWindow", "求解可行域"))
        self.groupBox_12.setTitle(_translate("MainWindow", "进针方案选择"))
        self.label_43.setText(_translate("MainWindow", "可选进针方案"))
        self.btn_clear_auto2.setText(_translate("MainWindow", "清空当前规划结果"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "并行规划"))

