# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PaintUi.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(938, 775)
        font = QtGui.QFont()
        font.setItalic(False)
        Form.setFont(font)
        self.page_png = QtWidgets.QLabel(Form)
        self.page_png.setGeometry(QtCore.QRect(20, 20, 121, 22))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.page_png.setFont(font)
        self.page_png.setStyleSheet("color: rgb(255, 255, 255);")
        self.page_png.setObjectName("page_png")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(1, 1, 519, 585))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_png = QtWidgets.QLabel(self.layoutWidget)
        self.label_png.setMinimumSize(QtCore.QSize(512, 512))
        self.label_png.setMaximumSize(QtCore.QSize(10000, 10000))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(14)
        self.label_png.setFont(font)
        self.label_png.setAutoFillBackground(False)
        self.label_png.setStyleSheet("background-color:rgb(0, 0, 0);")
        self.label_png.setText("")
        self.label_png.setAlignment(QtCore.Qt.AlignCenter)
        self.label_png.setObjectName("label_png")
        self.gridLayout.addWidget(self.label_png, 0, 0, 1, 4)
        self.label_target = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_target.setFont(font)
        self.label_target.setObjectName("label_target")
        self.gridLayout.addWidget(self.label_target, 1, 0, 1, 1)
        self.comboBox_target = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_target.setFont(font)
        self.comboBox_target.setObjectName("comboBox_target")
        self.comboBox_target.addItem("")
        self.comboBox_target.addItem("")
        self.comboBox_target.addItem("")
        self.comboBox_target.addItem("")
        self.comboBox_target.addItem("")
        self.comboBox_target.addItem("")
        self.comboBox_target.addItem("")
        self.comboBox_target.addItem("")
        self.comboBox_target.addItem("")
        self.comboBox_target.addItem("")
        self.comboBox_target.addItem("")
        self.comboBox_target.addItem("")
        self.comboBox_target.addItem("")
        self.gridLayout.addWidget(self.comboBox_target, 1, 1, 1, 1)
        self.label_skin = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_skin.setFont(font)
        self.label_skin.setObjectName("label_skin")
        self.gridLayout.addWidget(self.label_skin, 1, 2, 1, 1)
        self.comboBox_skin = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_skin.setFont(font)
        self.comboBox_skin.setObjectName("comboBox_skin")
        self.comboBox_skin.addItem("")
        self.comboBox_skin.addItem("")
        self.comboBox_skin.addItem("")
        self.comboBox_skin.addItem("")
        self.comboBox_skin.addItem("")
        self.comboBox_skin.addItem("")
        self.comboBox_skin.addItem("")
        self.comboBox_skin.addItem("")
        self.comboBox_skin.addItem("")
        self.comboBox_skin.addItem("")
        self.comboBox_skin.addItem("")
        self.comboBox_skin.addItem("")
        self.comboBox_skin.addItem("")
        self.gridLayout.addWidget(self.comboBox_skin, 1, 3, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_undo = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_undo.setFont(font)
        self.btn_undo.setObjectName("btn_undo")
        self.horizontalLayout.addWidget(self.btn_undo)
        self.btn_redo = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_redo.setFont(font)
        self.btn_redo.setObjectName("btn_redo")
        self.horizontalLayout.addWidget(self.btn_redo)
        self.btn_clear = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_clear.sizePolicy().hasHeightForWidth())
        self.btn_clear.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_clear.setFont(font)
        self.btn_clear.setObjectName("btn_clear")
        self.horizontalLayout.addWidget(self.btn_clear)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 4)
        self.layoutWidget.raise_()
        self.page_png.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "点标记窗口"))
        self.page_png.setText(_translate("Form", "0/0"))
        self.label_target.setText(_translate("Form", "标记针末端靶点"))
        self.comboBox_target.setItemText(0, _translate("Form", "不带标记"))
        self.comboBox_target.setItemText(1, _translate("Form", "1"))
        self.comboBox_target.setItemText(2, _translate("Form", "1.1"))
        self.comboBox_target.setItemText(3, _translate("Form", "1.2"))
        self.comboBox_target.setItemText(4, _translate("Form", "1.3"))
        self.comboBox_target.setItemText(5, _translate("Form", "2"))
        self.comboBox_target.setItemText(6, _translate("Form", "2.1"))
        self.comboBox_target.setItemText(7, _translate("Form", "2.2"))
        self.comboBox_target.setItemText(8, _translate("Form", "2.3"))
        self.comboBox_target.setItemText(9, _translate("Form", "3"))
        self.comboBox_target.setItemText(10, _translate("Form", "3.1"))
        self.comboBox_target.setItemText(11, _translate("Form", "3.2"))
        self.comboBox_target.setItemText(12, _translate("Form", "3.3"))
        self.label_skin.setText(_translate("Form", "标记皮肤进针点"))
        self.comboBox_skin.setItemText(0, _translate("Form", "不带标记"))
        self.comboBox_skin.setItemText(1, _translate("Form", "1"))
        self.comboBox_skin.setItemText(2, _translate("Form", "1.1"))
        self.comboBox_skin.setItemText(3, _translate("Form", "1.2"))
        self.comboBox_skin.setItemText(4, _translate("Form", "1.3"))
        self.comboBox_skin.setItemText(5, _translate("Form", "2"))
        self.comboBox_skin.setItemText(6, _translate("Form", "2.1"))
        self.comboBox_skin.setItemText(7, _translate("Form", "2.2"))
        self.comboBox_skin.setItemText(8, _translate("Form", "2.3"))
        self.comboBox_skin.setItemText(9, _translate("Form", "3"))
        self.comboBox_skin.setItemText(10, _translate("Form", "3.1"))
        self.comboBox_skin.setItemText(11, _translate("Form", "3.2"))
        self.comboBox_skin.setItemText(12, _translate("Form", "3.3"))
        self.btn_undo.setText(_translate("Form", "撤销"))
        self.btn_redo.setText(_translate("Form", "重做"))
        self.btn_clear.setText(_translate("Form", "清除该页标记"))

